### ISSUE TITLE
能否完善项目的配置

### ISSUE THREAD

**Issue by ghost** [wxt1997/Transformer-Transducer#3]
from rnnt.model import Transducer, Pre_encoder
这个rnnt是什么库？

你的项目结构不完整，缺少依赖文件，不清楚需要安装些什么

**Comment by oshindow** [comment]
> from rnnt.model import Transducer, Pre_encoder
> 这个rnnt是什么库？
> 
> 你的项目结构不完整，缺少依赖文件，不清楚需要安装些什么

抱歉，项目已经初步完善，欢迎使用。
