### ISSUE TITLE
能出一个中文demo吗

### ISSUE THREAD

**Issue by GrayScaleHY** [wxt1997/Transformer-Transducer#4]
请问可以出一个中文的demo吗？，您的README中的结果展示是thchs30，但是train.py用的是Timit数据集。

**Comment by oshindow** [comment]
> 请问可以出一个中文的demo吗？，您的README中的结果展示是thchs30，但是train.py用的是Timit数据集。

抱歉，可以测试普通话数据集Aishell-1。
